// 课题研究/组件统一/react-example.jsx
import React, { useEffect } from 'react';
import './shared-counter.js';

function ReactExample() {
  useEffect(() => {
    const counter = document.querySelector('shared-counter');
    counter.addEventListener('count-change', (e) => {
      console.log('Count changed:', e.detail);
    });
  }, []);

  return (
    <div>
      <h2>React中使用共享组件</h2>
      <shared-counter></shared-counter>
    </div>
  );
}

export default ReactExample;

// 课题研究/组件统一/vue-example.vue
<template>
  <div>
    <h2>Vue中使用共享组件</h2>
    <shared-counter @count-change="handleCountChange"></shared-counter>
  </div>
</template>

<script>
import './shared-counter.js';

export default {
  methods: {
    handleCountChange(e) {
      console.log('Count changed:', e.detail);
    }
  }
}
</script>
